services:
  postgres:
    image: postgres:18
    container_name: monorepo-template-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
